package Machine;

import java.io.Serializable;

/**
 * 機種詳細テーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MachineTable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 機種ID. */
	private Integer id;

	/** 機種名. */
	private String machineName;

	/** 天井. */
	private Integer ceiling;

	/** ゾーン. */
	private String zones;

	/** リセット. */
	private String riset;

	/** ヤメ時. */
	private String finish;

	/** 総ゲーム数. */
	private Integer totalGame;

	/** BIG. */
	private Integer bigGame;

	/** REG. */
	private Integer regGame;

	/** 設定差項目1. */
	private String setDif1;

	/** 設定差項目2. */
	private String setDif2;

	/** 設定1. */
	private Integer setting1;

	/** 設定2. */
	private Integer setting2;

	/** 設定3. */
	private Integer setting3;

	/** 設定4. */
	private Integer setting4;

	/** 設定5. */
	private Integer setting5;

	/** 設定6. */
	private Integer setting6;

	/**
	 * コンストラクタ.
	 */
	public MachineTable() {
	}

	/**
	 * 機種ID を設定します.
	 * 
	 * @param id
	 *            機種ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 機種ID を取得します.
	 * 
	 * @return 機種ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 機種名 を設定します.
	 * 
	 * @param machineName
	 *            機種名
	 */
	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}

	/**
	 * 機種名 を取得します.
	 * 
	 * @return 機種名
	 */
	public String getMachineName() {
		return this.machineName;
	}

	/**
	 * 天井 を設定します.
	 * 
	 * @param ceiling
	 *            天井
	 */
	public void setCeiling(Integer ceiling) {
		this.ceiling = ceiling;
	}

	/**
	 * 天井 を取得します.
	 * 
	 * @return 天井
	 */
	public Integer getCeiling() {
		return this.ceiling;
	}

	/**
	 * ゾーン を設定します.
	 * 
	 * @param zones
	 *            ゾーン
	 */
	public void setZones(String zones) {
		this.zones = zones;
	}

	/**
	 * ゾーン を取得します.
	 * 
	 * @return ゾーン
	 */
	public String getZones() {
		return this.zones;
	}

	/**
	 * リセット を設定します.
	 * 
	 * @param riset
	 *            リセット
	 */
	public void setRiset(String riset) {
		this.riset = riset;
	}

	/**
	 * リセット を取得します.
	 * 
	 * @return リセット
	 */
	public String getRiset() {
		return this.riset;
	}

	/**
	 * ヤメ時 を設定します.
	 * 
	 * @param finish
	 *            ヤメ時
	 */
	public void setFinish(String finish) {
		this.finish = finish;
	}

	/**
	 * ヤメ時 を取得します.
	 * 
	 * @return ヤメ時
	 */
	public String getFinish() {
		return this.finish;
	}

	/**
	 * 総ゲーム数 を設定します.
	 * 
	 * @param totalGame
	 *            総ゲーム数
	 */
	public void setTotalGame(Integer totalGame) {
		this.totalGame = totalGame;
	}

	/**
	 * 総ゲーム数 を取得します.
	 * 
	 * @return 総ゲーム数
	 */
	public Integer getTotalGame() {
		return this.totalGame;
	}

	/**
	 * BIG を設定します.
	 * 
	 * @param bigGame
	 *            BIG
	 */
	public void setBigGame(Integer bigGame) {
		this.bigGame = bigGame;
	}

	/**
	 * BIG を取得します.
	 * 
	 * @return BIG
	 */
	public Integer getBigGame() {
		return this.bigGame;
	}

	/**
	 * REG を設定します.
	 * 
	 * @param regGame
	 *            REG
	 */
	public void setRegGame(Integer regGame) {
		this.regGame = regGame;
	}

	/**
	 * REG を取得します.
	 * 
	 * @return REG
	 */
	public Integer getRegGame() {
		return this.regGame;
	}

	/**
	 * 設定差項目1 を設定します.
	 * 
	 * @param setDif1
	 *            設定差項目1
	 */
	public void setSetDif1(String setDif1) {
		this.setDif1 = setDif1;
	}

	/**
	 * 設定差項目1 を取得します.
	 * 
	 * @return 設定差項目1
	 */
	public String getSetDif1() {
		return this.setDif1;
	}

	/**
	 * 設定差項目2 を設定します.
	 * 
	 * @param setDif2
	 *            設定差項目2
	 */
	public void setSetDif2(String setDif2) {
		this.setDif2 = setDif2;
	}

	/**
	 * 設定差項目2 を取得します.
	 * 
	 * @return 設定差項目2
	 */
	public String getSetDif2() {
		return this.setDif2;
	}

	/**
	 * 設定1 を設定します.
	 * 
	 * @param setting1
	 *            設定1
	 */
	public void setSetting1(Integer setting1) {
		this.setting1 = setting1;
	}

	/**
	 * 設定1 を取得します.
	 * 
	 * @return 設定1
	 */
	public Integer getSetting1() {
		return this.setting1;
	}

	/**
	 * 設定2 を設定します.
	 * 
	 * @param setting2
	 *            設定2
	 */
	public void setSetting2(Integer setting2) {
		this.setting2 = setting2;
	}

	/**
	 * 設定2 を取得します.
	 * 
	 * @return 設定2
	 */
	public Integer getSetting2() {
		return this.setting2;
	}

	/**
	 * 設定3 を設定します.
	 * 
	 * @param setting3
	 *            設定3
	 */
	public void setSetting3(Integer setting3) {
		this.setting3 = setting3;
	}

	/**
	 * 設定3 を取得します.
	 * 
	 * @return 設定3
	 */
	public Integer getSetting3() {
		return this.setting3;
	}

	/**
	 * 設定4 を設定します.
	 * 
	 * @param setting4
	 *            設定4
	 */
	public void setSetting4(Integer setting4) {
		this.setting4 = setting4;
	}

	/**
	 * 設定4 を取得します.
	 * 
	 * @return 設定4
	 */
	public Integer getSetting4() {
		return this.setting4;
	}

	/**
	 * 設定5 を設定します.
	 * 
	 * @param setting5
	 *            設定5
	 */
	public void setSetting5(Integer setting5) {
		this.setting5 = setting5;
	}

	/**
	 * 設定5 を取得します.
	 * 
	 * @return 設定5
	 */
	public Integer getSetting5() {
		return this.setting5;
	}

	/**
	 * 設定6 を設定します.
	 * 
	 * @param setting6
	 *            設定6
	 */
	public void setSetting6(Integer setting6) {
		this.setting6 = setting6;
	}

	/**
	 * 設定6 を取得します.
	 * 
	 * @return 設定6
	 */
	public Integer getSetting6() {
		return this.setting6;
	}


}
